/**
 * security.txt generator — creates a valid RFC 9116 security.txt file
 * Supports interactive prompts and non-interactive flag-based usage for CI
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { createInterface } from 'node:readline';
import { dirname, join, resolve } from 'node:path';
import chalk from 'chalk';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Fields that make up a security.txt file */
export interface SecurityTxtFields {
  readonly contact: string;
  readonly expires: string;
  readonly preferredLanguages: string;
  readonly policy?: string;
  readonly acknowledgments?: string;
}

/** CLI options for non-interactive mode */
export interface SecurityTxtOptions {
  readonly contact?: string;
  readonly expires?: string;
  readonly languages?: string;
  readonly policy?: string;
  readonly acknowledgments?: string;
  readonly path: string;
}

// ---------------------------------------------------------------------------
// Pure functions (exported for testing)
// ---------------------------------------------------------------------------

/**
 * Generate security.txt file content from fields.
 * Returns a valid RFC 9116 security.txt string.
 */
export function generateSecurityTxt(fields: SecurityTxtFields): string {
  const lines: string[] = [
    '# security.txt — generated by Bastion',
    '# https://securitytxt.org/ | RFC 9116',
    '',
    `Contact: ${fields.contact}`,
    `Expires: ${fields.expires}`,
  ];

  if (fields.preferredLanguages) {
    lines.push(`Preferred-Languages: ${fields.preferredLanguages}`);
  }

  if (fields.policy) {
    lines.push(`Policy: ${fields.policy}`);
  }

  if (fields.acknowledgments) {
    lines.push(`Acknowledgments: ${fields.acknowledgments}`);
  }

  lines.push('');

  return lines.join('\n');
}

/** Returns an ISO 8601 date string one year from now */
export function defaultExpiresDate(): string {
  const date = new Date();
  date.setFullYear(date.getFullYear() + 1);
  return date.toISOString();
}

/** Normalize a contact value — prefix mailto: for bare email addresses */
export function normalizeContact(value: string): string {
  const trimmed = value.trim();
  if (
    !trimmed.startsWith('mailto:') &&
    !trimmed.startsWith('https://') &&
    trimmed.includes('@')
  ) {
    return `mailto:${trimmed}`;
  }
  return trimmed;
}

/** Validate a contact value. Returns error message or null if valid */
export function validateContact(value: string): string | null {
  const trimmed = value.trim();
  if (!trimmed) {
    return 'Contact is required';
  }
  if (
    !trimmed.startsWith('mailto:') &&
    !trimmed.startsWith('https://') &&
    !trimmed.includes('@')
  ) {
    return 'Contact must be an email address, mailto: URI, or https:// URL';
  }
  return null;
}

/** Validate an Expires date string. Returns error message or null if valid */
export function validateExpires(value: string): string | null {
  const date = new Date(value);
  if (isNaN(date.getTime())) {
    return 'Invalid date format. Use ISO 8601 (e.g., 2027-04-15T00:00:00.000Z)';
  }
  if (date.getTime() <= Date.now()) {
    return 'Expires date must be in the future';
  }
  return null;
}

// ---------------------------------------------------------------------------
// I/O helpers (not exported — interactive prompts, not unit-tested)
// ---------------------------------------------------------------------------

/** Prompt user for a single field value */
function promptField(
  rl: ReturnType<typeof createInterface>,
  question: string,
  defaultValue?: string,
): Promise<string> {
  const suffix = defaultValue ? ` [${defaultValue}]` : '';
  return new Promise<string>((res) => {
    rl.question(`  ${question}${suffix}: `, (answer) => {
      res(answer.trim() || defaultValue || '');
    });
  });
}

/** Run interactive prompts to gather all security.txt fields */
async function promptForFields(
  rl: ReturnType<typeof createInterface>,
): Promise<{ readonly fields: SecurityTxtFields; readonly writeToRoot: boolean }> {
  console.log();
  console.log(chalk.bold.cyan('  security.txt Generator'));
  console.log(chalk.dim('  Creates a valid security.txt file per RFC 9116'));
  console.log();

  // Contact (required — loop until valid)
  let contact = '';
  while (!contact) {
    const raw = await promptField(rl, 'Contact email or URL');
    const error = validateContact(raw);
    if (error) {
      console.log(chalk.red(`  ${error}`));
    } else {
      contact = normalizeContact(raw);
    }
  }

  const expires = await promptField(rl, 'Expires date (ISO 8601)', defaultExpiresDate());
  const preferredLanguages = await promptField(rl, 'Preferred-Languages', 'en');
  const policy = await promptField(rl, 'Policy URL (optional)');
  const acknowledgments = await promptField(rl, 'Acknowledgments URL (optional)');

  const rootAnswer = await promptField(rl, 'Also create at project root? (y/N)');
  const writeToRoot =
    rootAnswer.toLowerCase() === 'y' || rootAnswer.toLowerCase() === 'yes';

  return {
    fields: {
      contact,
      expires,
      preferredLanguages,
      ...(policy ? { policy } : {}),
      ...(acknowledgments ? { acknowledgments } : {}),
    },
    writeToRoot,
  };
}

/** Write security.txt content to one or more locations under projectPath */
async function writeSecurityTxtFiles(
  projectPath: string,
  content: string,
  locations: readonly string[],
): Promise<readonly string[]> {
  const written: string[] = [];

  for (const location of locations) {
    const fullPath = join(projectPath, location);
    await mkdir(dirname(fullPath), { recursive: true });
    await writeFile(fullPath, content, 'utf-8');
    written.push(fullPath);
  }

  return written;
}

/** Print the generated file content and save locations */
function printResult(content: string, paths: readonly string[]): void {
  console.log();
  console.log(chalk.bold.green('  \u2713 security.txt generated'));
  console.log();
  console.log(chalk.dim('  Contents:'));
  console.log();
  for (const line of content.split('\n')) {
    if (line) {
      console.log(`    ${line}`);
    }
  }
  console.log();
  for (const p of paths) {
    console.log(`  ${chalk.dim('Saved:')} ${p}`);
  }
  console.log();
}

// ---------------------------------------------------------------------------
// CLI action
// ---------------------------------------------------------------------------

/**
 * Run the security.txt generator.
 * If --contact is provided, runs in non-interactive mode (CI-friendly).
 * Otherwise, prompts the user interactively.
 */
export async function runSecurityTxtGenerator(
  options: SecurityTxtOptions,
): Promise<void> {
  const projectPath = resolve(options.path);

  try {
    let fields: SecurityTxtFields;
    let writeToRoot = false;

    if (options.contact) {
      // Non-interactive: build fields from CLI flags
      const contact = normalizeContact(options.contact);
      const contactError = validateContact(contact);
      if (contactError) {
        console.error(chalk.red(`\n  Error: ${contactError}\n`));
        process.exitCode = 1;
        return;
      }

      const expires = options.expires ?? defaultExpiresDate();
      const expiresError = validateExpires(expires);
      if (expiresError) {
        console.error(chalk.red(`\n  Error: ${expiresError}\n`));
        process.exitCode = 1;
        return;
      }

      fields = {
        contact,
        expires,
        preferredLanguages: options.languages ?? 'en',
        ...(options.policy ? { policy: options.policy } : {}),
        ...(options.acknowledgments
          ? { acknowledgments: options.acknowledgments }
          : {}),
      };
    } else {
      // Interactive: prompt for all fields
      const rl = createInterface({
        input: process.stdin,
        output: process.stdout,
      });
      try {
        const result = await promptForFields(rl);
        fields = result.fields;
        writeToRoot = result.writeToRoot;
      } finally {
        rl.close();
      }
    }

    const content = generateSecurityTxt(fields);
    const locations: string[] = ['.well-known/security.txt'];
    if (writeToRoot) {
      locations.push('security.txt');
    }

    const written = await writeSecurityTxtFiles(projectPath, content, locations);
    printResult(content, written);
  } catch (error) {
    console.error(
      chalk.red(
        `\n  Error: ${error instanceof Error ? error.message : String(error)}\n`,
      ),
    );
    process.exitCode = 1;
  }
}
